{ config, lib, pkgs, ... }:

{
  home.activation.claudeConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] (''
    # Single files
    install -D -m 644 ${./claude/CLAUDE.md} ${config.home.homeDirectory}/.claude/CLAUDE.md
    # settings.json carries an @HOME@ placeholder for the herdr hook command,
    # since Claude Code takes a literal command string with no home expansion.
    install -D -m 644 ${./claude/settings.json} ${config.home.homeDirectory}/.claude/settings.json
    # substituteInPlace is a nixpkgs build-phase helper and is not defined in
    # activation scripts, so this uses sed directly.
    ${pkgs.gnused}/bin/sed -i 's|@HOME@|${config.home.homeDirectory}|g' \
      ${config.home.homeDirectory}/.claude/settings.json

    # Agent-state hook generated by `herdr integration install claude`. Vendored
    # so a rebuild does not drop it -- herdr writes into ~/.claude directly,
    # which this activation script overwrites. Re-run that command to update it,
    # then copy the result back here (HERDR_INTEGRATION_VERSION marks the rev).
    install -D -m 755 ${./claude/hooks/herdr-agent-state.sh} ${config.home.homeDirectory}/.claude/hooks/herdr-agent-state.sh
    install -D -m 644 ${./claude/keybindings.json} ${config.home.homeDirectory}/.claude/keybindings.json
    install -D -m 755 ${./claude/statusline.py} ${config.home.homeDirectory}/.claude/statusline.py
    install -D -m 755 ${./claude/statusline-command.sh} ${config.home.homeDirectory}/.claude/statusline-command.sh
    install -D -m 755 ${./claude/scripts/deny-check.sh} ${config.home.homeDirectory}/.claude/scripts/deny-check.sh
    install -D -m 644 ${./claude/cat.mp3} ${config.home.homeDirectory}/.claude/cat.mp3
    install -D -m 644 ${./claude/cat-amae.mp3} ${config.home.homeDirectory}/.claude/cat-amae.mp3
    install -D -m 644 ${./claude/themes/midnight.json} ${config.home.homeDirectory}/.claude/themes/midnight.json

    # skills (chmod before cp to handle read-only files from previous runs)
    mkdir -p ${config.home.homeDirectory}/.claude/skills
    chmod -R u+w ${config.home.homeDirectory}/.claude/skills 2>/dev/null || true
    cp -r ${./claude/skills}/. ${config.home.homeDirectory}/.claude/skills/
    # _shared is a source-only dir (holds the diff-page script shared by
    # diff-explain and diff-review); it is not a skill, so drop it from the
    # deployed skills tree and fan the script out into each skill's scripts/.
    # chmod first: files copied from the nix store are read-only, and macOS
    # rm refuses to remove read-only files.
    chmod -R u+w ${config.home.homeDirectory}/.claude/skills/_shared 2>/dev/null || true
    rm -rf ${config.home.homeDirectory}/.claude/skills/_shared
    for skill in diff-explain diff-review; do
      mkdir -p ${config.home.homeDirectory}/.claude/skills/$skill/scripts
      install -m 755 ${./claude/skills/_shared/build_diff_page.py} \
        ${config.home.homeDirectory}/.claude/skills/$skill/scripts/build_diff_page.py
    done

    # commands
    mkdir -p ${config.home.homeDirectory}/.claude/commands
    chmod -R u+w ${config.home.homeDirectory}/.claude/commands 2>/dev/null || true
    cp -r ${./claude/commands}/. ${config.home.homeDirectory}/.claude/commands/

    # ponytail (vendored plugin, see claude/ponytail/UPSTREAM.md).
    # Upstream ships as a Claude Code plugin, but this repo deploys it by hand so
    # a rebuild owns it declaratively. Three parts: the six SKILL.md skills and the
    # six commands go into the shared skills/commands trees; the Node hooks that
    # inject the ruleset every session (the "always on" effect, the plugin's core)
    # live under ~/.claude/ponytail/hooks and are wired up in settings.json.
    # Commands are converted from upstream .toml to .md ({{args}} -> $ARGUMENTS)
    # because ~/.claude/commands only reliably supports the .md form.
    for skill in ponytail ponytail-review ponytail-audit ponytail-debt ponytail-gain ponytail-help; do
      mkdir -p ${config.home.homeDirectory}/.claude/skills/$skill
      chmod -R u+w ${config.home.homeDirectory}/.claude/skills/$skill 2>/dev/null || true
      cp -r ${./claude/ponytail/skills}/$skill/. ${config.home.homeDirectory}/.claude/skills/$skill/
    done
    cp ${./claude/ponytail/commands}/*.md ${config.home.homeDirectory}/.claude/commands/
    # Hooks read the SKILL body via ../skills/ponytail/SKILL.md relative to the
    # hooks dir, so keep skills/ alongside hooks/ under the ponytail root too.
    mkdir -p ${config.home.homeDirectory}/.claude/ponytail
    chmod -R u+w ${config.home.homeDirectory}/.claude/ponytail 2>/dev/null || true
    cp -r ${./claude/ponytail/hooks} ${config.home.homeDirectory}/.claude/ponytail/hooks
    cp -r ${./claude/ponytail/skills} ${config.home.homeDirectory}/.claude/ponytail/skills
    chmod -R u+w ${config.home.homeDirectory}/.claude/ponytail

    # codex
    #
    # codex writes runtime state back into config.toml -- notably [hooks.state],
    # which records a trust hash per hook. Overwriting the file wholesale drops
    # that, and codex then treats the herdr hook as untrusted. So the managed
    # config is written first and any [hooks.state] from the previous file is
    # appended back.
    codexConfig=${config.home.homeDirectory}/.codex/config.toml
    codexState=$(mktemp)
    if [ -f "$codexConfig" ]; then
      ${pkgs.gnused}/bin/sed -n '/^\[hooks\.state/,$p' "$codexConfig" > "$codexState"
    fi
    install -D -m 644 ${./claude/codex/config.toml} "$codexConfig"
    if [ -s "$codexState" ]; then
      printf '\n' >> "$codexConfig"
      cat "$codexState" >> "$codexConfig"
    fi
    rm -f "$codexState"

    # Agent-state hook generated by `herdr integration install codex`, vendored
    # for the same reason as the claude one above: herdr writes into ~/.codex
    # directly and this activation overwrites it. hooks.json carries an @HOME@
    # placeholder because codex takes a literal command string.
    install -D -m 755 ${./claude/codex/hooks/herdr-agent-state.sh} ${config.home.homeDirectory}/.codex/herdr-agent-state.sh
    # Stop hook: summarizes the conversation once per session and reports it as
    # the $codex_title sidebar token (see ui.sidebar.agents.rows_by_agent in
    # herdr.nix). Vendored here because this activation owns hooks.json -- a
    # hook added only on the live file is wiped by the next rebuild.
    install -D -m 755 ${./claude/codex/hooks/codex-title.sh} ${config.home.homeDirectory}/.codex/codex-title.sh
    install -D -m 644 ${./claude/codex/hooks.json} ${config.home.homeDirectory}/.codex/hooks.json
    ${pkgs.gnused}/bin/sed -i 's|@HOME@|${config.home.homeDirectory}|g' \
      ${config.home.homeDirectory}/.codex/hooks.json
    mkdir -p ${config.home.homeDirectory}/.codex/skills/to-claude
    chmod -R u+w ${config.home.homeDirectory}/.codex/skills 2>/dev/null || true
    cp -r ${./claude/codex/skills}/. ${config.home.homeDirectory}/.codex/skills/
    # shared skills (single source in claude/skills, deployed to both claude and codex)
    # copy CONTENTS into a named dir so the target is ~/.codex/skills/<skill>
    # (not the nix store's <hash>-<skill> path), and fan out the shared script.
    for skill in diff-explain diff-review; do
      mkdir -p ${config.home.homeDirectory}/.codex/skills/$skill/scripts
      cp -r ${./claude/skills}/$skill/. ${config.home.homeDirectory}/.codex/skills/$skill/
      install -m 755 ${./claude/skills/_shared/build_diff_page.py} \
        ${config.home.homeDirectory}/.codex/skills/$skill/scripts/build_diff_page.py
    done
    # skills vendored from third-party repos (see claude/VENDORED-SKILLS.md
    # for origins and update procedure). Plain copies -- no shared-script
    # fan-out needed.
    for skill in paper-details html documenting-with-sources writing-quotation explain \
                 grilling grill-me navigating quizzing tutoring; do
      mkdir -p ${config.home.homeDirectory}/.codex/skills/$skill
      cp -r ${./claude/skills}/$skill/. ${config.home.homeDirectory}/.codex/skills/$skill/
    done
    # herdr ships its own agent skill. It builds on every supported platform,
    # so unlike terminal-browser below it needs no per-system guard.
    for base in .claude .codex; do
      install -D -m 644 ${pkgs.herdr}/share/herdr/skills/herdr/SKILL.md \
        ${config.home.homeDirectory}/$base/skills/herdr/SKILL.md
    done
  ''
  # terminal-browser ships its own agent skill. Upstream only builds for Apple
  # Silicon, so referencing the package on any other system would throw.
  + lib.optionalString (pkgs.stdenv.hostPlatform.system == "aarch64-darwin") ''
    for base in .claude .codex; do
      install -D -m 644 ${pkgs.terminal-browser}/share/terminal-browser/SKILL.md \
        ${config.home.homeDirectory}/$base/skills/terminal-browser/SKILL.md
    done
  '');
}
